language: python
python:
  - "2.7"
install:
  - python -m pip install --upgrade .
  - python -m pip install pylint
  - python -m pip install python-coveralls
script:
  - ./run_presubmit.sh
after_success:
  # Upload coverage data to coveralls.io.
  - coveralls
