# Copyright 2019 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generates hashing code for string."""

import sys

import farmhash


def generate_int64_hash_code(string):
  # type: (str) -> int
  """Generates a forever-fixed int64 hash code for `string`.

  The hash code generated by farmhash.fingerprint64 is unsigned. The int64 field
  in BQ is signed. -sys.maxint - 1 is used to create a 1 to 1 mapping from
  unsigned int to signed int.
  """
  return farmhash.fingerprint64(string) - sys.maxint - 1
